/**
 * Test `*OrDefault` functions.
 */

// This code has been automatically generated by:
// dev_scripts/test_codegen/generate_test_for_get_X_or_default.py
// Do NOT edit or append.

import * as path from "path";
import * as fs from "fs";

import * as AasStringification from "../src/stringification";
import * as AasTypes from "../src/types";
import * as TestCommon from "./common";
import * as TestCommonJsonization from "./commonJsonization";

/**
 * Represent explicitly a literal of an enumeration.
 */
class EnumerationLiteral {
  constructor(public enumerationName: string, public literalName) {
    // Intentionally empty.
  }

  toString(): string {
    return `${this.enumerationName}.${this.literalName}`;
  }
}

/**
 * Represent a value such that we can immediately check whether it is the default value
 * or the set one.
 *
 * @remark
 * We compare it against the recorded golden file, if not {@link common.RECORD_MODE}.
 * Otherwise, when {@link common.RECORD_MODE} is set, we re-record the golden file.
 *
 * @param value - to be represented
 * @param expectedPath - to the golden file
 */
function compareOrRecordValue(
  value: boolean | number | string | null | EnumerationLiteral | AasTypes.Class,
  expectedPath: string
): void {
  let got = "";
  if (
    typeof value === "boolean" ||
    typeof value === "number" ||
    typeof value === "string" ||
    value === null
  ) {
    got = JSON.stringify(value);
  } else if (value instanceof EnumerationLiteral) {
    got = value.toString();
  } else if (value instanceof AasTypes.Class) {
    got = TestCommon.traceMark(value);
  } else {
    throw new Error(`We do not know how to represent the value ${value}`);
  }

  // NOTE (mristin, 2022-12-09):
  // We add a new line for POSIX systems which prefer a new line
  // at the end of the file.
  got += "\n";

  if (TestCommon.RECORD_MODE) {
    const parent = path.dirname(expectedPath);
    if (!fs.existsSync(parent)) {
      fs.mkdirSync(parent, { recursive: true });
    }
    fs.writeFileSync(expectedPath, got, "utf-8");
  } else {
    if (!fs.existsSync(expectedPath)) {
      throw new Error(
        `The file with the recorded value does not exist: ${expectedPath}; ` +
          `you probably want to set the environment ` +
          `variable ${TestCommon.RECORD_MODE_ENVIRONMENT_VARIABLE_NAME}?`
      );
    }

    const expected = fs.readFileSync(expectedPath, "utf-8").replace(/\r\n/g, "\n");
    expect(got).toStrictEqual(expected);
  }
}

test("Extension.valueTypeOrDefault with non-default", () => {
  const instance = TestCommonJsonization.loadMaximalExtension();

  const value = new EnumerationLiteral(
    "DataTypeDefXsd",
    AasStringification.mustDataTypeDefXsdToString(instance.valueTypeOrDefault())
  );

  compareOrRecordValue(
    value,
    path.join(
      TestCommon.TEST_DATA_DIR,
      "xOrDefault",
      "Extension",
      "valueTypeOrDefault.non-default.json"
    )
  );
});

test("Extension.valueTypeOrDefault with default", () => {
  const instance = TestCommonJsonization.loadMinimalExtension();

  const value = new EnumerationLiteral(
    "DataTypeDefXsd",
    AasStringification.mustDataTypeDefXsdToString(instance.valueTypeOrDefault())
  );

  compareOrRecordValue(
    value,
    path.join(
      TestCommon.TEST_DATA_DIR,
      "xOrDefault",
      "Extension",
      "valueTypeOrDefault.default.json"
    )
  );
});

test("Qualifier.kindOrDefault with non-default", () => {
  const instance = TestCommonJsonization.loadMaximalQualifier();

  const value = new EnumerationLiteral(
    "QualifierKind",
    AasStringification.mustQualifierKindToString(instance.kindOrDefault())
  );

  compareOrRecordValue(
    value,
    path.join(
      TestCommon.TEST_DATA_DIR,
      "xOrDefault",
      "Qualifier",
      "kindOrDefault.non-default.json"
    )
  );
});

test("Qualifier.kindOrDefault with default", () => {
  const instance = TestCommonJsonization.loadMinimalQualifier();

  const value = new EnumerationLiteral(
    "QualifierKind",
    AasStringification.mustQualifierKindToString(instance.kindOrDefault())
  );

  compareOrRecordValue(
    value,
    path.join(
      TestCommon.TEST_DATA_DIR,
      "xOrDefault",
      "Qualifier",
      "kindOrDefault.default.json"
    )
  );
});

test("Submodel.kindOrDefault with non-default", () => {
  const instance = TestCommonJsonization.loadMaximalSubmodel();

  const value = new EnumerationLiteral(
    "ModellingKind",
    AasStringification.mustModellingKindToString(instance.kindOrDefault())
  );

  compareOrRecordValue(
    value,
    path.join(
      TestCommon.TEST_DATA_DIR,
      "xOrDefault",
      "Submodel",
      "kindOrDefault.non-default.json"
    )
  );
});

test("Submodel.kindOrDefault with default", () => {
  const instance = TestCommonJsonization.loadMinimalSubmodel();

  const value = new EnumerationLiteral(
    "ModellingKind",
    AasStringification.mustModellingKindToString(instance.kindOrDefault())
  );

  compareOrRecordValue(
    value,
    path.join(
      TestCommon.TEST_DATA_DIR,
      "xOrDefault",
      "Submodel",
      "kindOrDefault.default.json"
    )
  );
});

test("SubmodelElementList.orderRelevantOrDefault with non-default", () => {
  const instance = TestCommonJsonization.loadMaximalSubmodelElementList();

  const value = instance.orderRelevantOrDefault();

  compareOrRecordValue(
    value,
    path.join(
      TestCommon.TEST_DATA_DIR,
      "xOrDefault",
      "SubmodelElementList",
      "orderRelevantOrDefault.non-default.json"
    )
  );
});

test("SubmodelElementList.orderRelevantOrDefault with default", () => {
  const instance = TestCommonJsonization.loadMinimalSubmodelElementList();

  const value = instance.orderRelevantOrDefault();

  compareOrRecordValue(
    value,
    path.join(
      TestCommon.TEST_DATA_DIR,
      "xOrDefault",
      "SubmodelElementList",
      "orderRelevantOrDefault.default.json"
    )
  );
});

test("Property.categoryOrDefault with non-default", () => {
  const instance = TestCommonJsonization.loadMaximalProperty();

  const value = instance.categoryOrDefault();

  compareOrRecordValue(
    value,
    path.join(
      TestCommon.TEST_DATA_DIR,
      "xOrDefault",
      "Property",
      "categoryOrDefault.non-default.json"
    )
  );
});

test("Property.categoryOrDefault with default", () => {
  const instance = TestCommonJsonization.loadMinimalProperty();

  const value = instance.categoryOrDefault();

  compareOrRecordValue(
    value,
    path.join(
      TestCommon.TEST_DATA_DIR,
      "xOrDefault",
      "Property",
      "categoryOrDefault.default.json"
    )
  );
});

test("MultiLanguageProperty.categoryOrDefault with non-default", () => {
  const instance = TestCommonJsonization.loadMaximalMultiLanguageProperty();

  const value = instance.categoryOrDefault();

  compareOrRecordValue(
    value,
    path.join(
      TestCommon.TEST_DATA_DIR,
      "xOrDefault",
      "MultiLanguageProperty",
      "categoryOrDefault.non-default.json"
    )
  );
});

test("MultiLanguageProperty.categoryOrDefault with default", () => {
  const instance = TestCommonJsonization.loadMinimalMultiLanguageProperty();

  const value = instance.categoryOrDefault();

  compareOrRecordValue(
    value,
    path.join(
      TestCommon.TEST_DATA_DIR,
      "xOrDefault",
      "MultiLanguageProperty",
      "categoryOrDefault.default.json"
    )
  );
});

test("Range.categoryOrDefault with non-default", () => {
  const instance = TestCommonJsonization.loadMaximalRange();

  const value = instance.categoryOrDefault();

  compareOrRecordValue(
    value,
    path.join(
      TestCommon.TEST_DATA_DIR,
      "xOrDefault",
      "Range",
      "categoryOrDefault.non-default.json"
    )
  );
});

test("Range.categoryOrDefault with default", () => {
  const instance = TestCommonJsonization.loadMinimalRange();

  const value = instance.categoryOrDefault();

  compareOrRecordValue(
    value,
    path.join(
      TestCommon.TEST_DATA_DIR,
      "xOrDefault",
      "Range",
      "categoryOrDefault.default.json"
    )
  );
});

test("ReferenceElement.categoryOrDefault with non-default", () => {
  const instance = TestCommonJsonization.loadMaximalReferenceElement();

  const value = instance.categoryOrDefault();

  compareOrRecordValue(
    value,
    path.join(
      TestCommon.TEST_DATA_DIR,
      "xOrDefault",
      "ReferenceElement",
      "categoryOrDefault.non-default.json"
    )
  );
});

test("ReferenceElement.categoryOrDefault with default", () => {
  const instance = TestCommonJsonization.loadMinimalReferenceElement();

  const value = instance.categoryOrDefault();

  compareOrRecordValue(
    value,
    path.join(
      TestCommon.TEST_DATA_DIR,
      "xOrDefault",
      "ReferenceElement",
      "categoryOrDefault.default.json"
    )
  );
});

test("Blob.categoryOrDefault with non-default", () => {
  const instance = TestCommonJsonization.loadMaximalBlob();

  const value = instance.categoryOrDefault();

  compareOrRecordValue(
    value,
    path.join(
      TestCommon.TEST_DATA_DIR,
      "xOrDefault",
      "Blob",
      "categoryOrDefault.non-default.json"
    )
  );
});

test("Blob.categoryOrDefault with default", () => {
  const instance = TestCommonJsonization.loadMinimalBlob();

  const value = instance.categoryOrDefault();

  compareOrRecordValue(
    value,
    path.join(
      TestCommon.TEST_DATA_DIR,
      "xOrDefault",
      "Blob",
      "categoryOrDefault.default.json"
    )
  );
});

test("File.categoryOrDefault with non-default", () => {
  const instance = TestCommonJsonization.loadMaximalFile();

  const value = instance.categoryOrDefault();

  compareOrRecordValue(
    value,
    path.join(
      TestCommon.TEST_DATA_DIR,
      "xOrDefault",
      "File",
      "categoryOrDefault.non-default.json"
    )
  );
});

test("File.categoryOrDefault with default", () => {
  const instance = TestCommonJsonization.loadMinimalFile();

  const value = instance.categoryOrDefault();

  compareOrRecordValue(
    value,
    path.join(
      TestCommon.TEST_DATA_DIR,
      "xOrDefault",
      "File",
      "categoryOrDefault.default.json"
    )
  );
});
